# Generated by Django 2.2.6 on 2019-10-23 04:38

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_feed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feed',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='feeds'),
        ),
    ]
